### ISSUE TITLE
3.0.0: ClassNotFoundException: com.amazonaws.1.9.39.shade.jmx.SdkMBeanRegistrySupport when running Mule

### ISSUE THREAD

**Issue by hiper2d** [mulesoft/sqs-connector#53]
Hi guys,

I posted my problem on the StackOverflow: http://stackoverflow.com/questions/31525347/classnotfoundexception-when-using-the-mule-amazon-sqs-connector

I get the error from the title right after running the application. It's visible only when I set log4j.logger.com.amazonaws=DEBUG in my log4j.properties. Could you clarify this behavior? Thanks.

**Comment by karthikanantha** [comment]
Hi,
This behavior was observed as we configured the shading configuration to minimiseJar=true and hence the internal classes required by the AWS JMX classes were not packaged with.

You can ignore this logging as its logged only when the logger is to debug mode. This has no impact on the behavior of the connector.

This has been fixed in the upcoming v3.1.0 release of the connector along with other minor bug fixes.

Thanks

**Comment by hiper2d** [comment]
Thanks for the response, please close the issue.
